
USE SALESANALYTICSDB
------------------------------------------

    CREATE TABLE customers (                      
    id INT PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    age INT,
    country VARCHAR(50),
    amount_spend INT);

    INSERT INTO CUSTOMERS (ID, USER_NAME, AGE, COUNTRY, AMOUNT_SPEND)
    VALUES
    (1, 'RAHUL' , 25, 'INDIA', 15000),
    (2, 'DIYA' , 28, 'AMERICA', 25000),
    (3, 'REKHA' , 30, 'INDIA', 20000),
    (4, 'NAMRA' , 24, 'UK', 22000),
    (5, 'AYUSHI' , 22, 'INDIA', 20000),
    (6, 'JALPA' , 40, 'AMERICA', 30000),
    (7, 'DIVYANSH' , 28, 'CANADA', 28000),
    (8, 'CHETAN' , 35, 'LONDON', 35000),
    (9, 'NIKITA' , 23, 'USA', 35000),
    (10, 'KUNAL' , 29, 'INDIA', 40000),
    (11, 'MOHIT' , 28, 'LONDON', 29000),
    (12, 'LAVYA' , 35, 'CANADA', 30000),
    (13, 'MANALI' , 30, 'AMERICA', 25000),
    (14, 'KHUSHI' , 29, 'UK', 35000),
    (15, 'SNEH' , 22, 'INDIA', 20000);

     SELECT * FROM CUSTOMERS

---TASK 5
SELECT USER_NAME, AGE,
COUNTRY
FROM CUSTOMERS;

----TASK 6
SELECT USER_NAME,
COUNTRY, AMOUNT_SPEND
FROM CUSTOMERS;

----TASK 7
SELECT*
FROM CUSTOMERS
WHERE AMOUNT_SPEND >
35000;

---TASK 8
SELECT*
FROM CUSTOMERS
WHERE AGE < 30;

---- TASK 9 
SELECT*
FROM CUSTOMERS
WHERE COUNTRY = 'INDIA';

----TASK 10
SELECT*
FROM CUSTOMERS 
WHERE AMOUNT_SPEND <
20000;

---TASK 11
SELECT*
FROM CUSTOMERS
WHERE AGE < 30
 AND AMOUNT_SPEND >
 30000;

----TASK 12
SELECT *
FROM CUSTOMERS
WHERE COUNTRY = 'INDIA'
 AND AMOUNT_SPEND >
 35000;

----TASK 13
SELECT *
FROM CUSTOMERS
WHERE COUNTRY = 'INDIA'
   OR COUNTRY = 'USA';

   ---TASK 14
   SELECT *
   FROM CUSTOMERS 
   WHERE (COUNTRY = 'INDIA'
    OR COUNTRY = 'USA')
      AND AMOUNT_SPEND >
      35000;

---TASK 15
SELECT *
FROM CUSTOMERS
WHERE NOT COUNTRY =
'INDIA';

---TASK 16
SELECT *
FROM CUSTOMERS
ORDER BY AMOUNT_SPEND
ASC;

---TASK 17
SELECT *
FROM CUSTOMERS 
ORDER BY AMOUNT_SPEND
DESC;

---TASK 18
SELECT ID,
AGE, COUNTRY,
AMOUNT_SPEND
FROM CUSTOMERS
ORDER BY AGE ASC;

---TASK 19
SELECT *
FROM customers 
WHERE AGE BETWEEN 25 AND 40
 AND AMOUNT_SPEND > 30000
 AND (COUNTRY = 'INDIA' 
 OR COUNTRY = 'USA')
 ORDER BY AMOUNT_SPEND
 DESC;

 ---TASK 20
 SELECT *
 FROM CUSTOMERS
 WHERE age >= 30 AND amount_spend > 40000 AND country != 'INDIA' ORDER BY amount_spend DESC;


